### ISSUE TITLE
TC 2- Reference Organisation in Coverage Selbstzahler (Für Stufe 2 als TC - 3 gelöst)

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#179]
Organisation should be part of payor Reference vor PKV

see https://chat.fhir.org/#narrow/stream/287581-german.2Fisik/topic/.5BBasis.5D.20Coverage/near/322082286

- [ ] SOLLTE als workaround in STufe / neues Feature eingehen
- [x] MUSS in Stufe 3 als breaking change eingehen (ggf. für diesen Change auch PKV involvieren)
- [ ] Ansprechen: Private auch Zusatzversicherung als Case berücksichtigen
```[tasklist]
### Tasks
- [ ] PTDATA-691
```

**Comment by f-peverali** [comment]
@JoshuaBolte könntest Du dir das Thema in zulip anschauen? Würde mich zur Umsetzung gerne mit dir abstimmen.

**Comment by f-peverali** [comment]
Idee hier (siehe Simone in zulip) : analog zu unserem GKV-profil identifier nutzen (ggf. mit anderem identifier). Identifier muss nicht zwingend nach außen auflösbar sein, sondern ggf. nur Krankenhaus-intern

**Comment by f-peverali** [comment]
Für Stufe 3 Umgesetzt als Pull Request
