### ISSUE TITLE
HTTP return anpassen

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#308]
https://github.com/gematik/spec-ISiK-Basismodul/blob/6e2131d4b87ddd90397fadc006cb4cc3aa2ef724/ImplementationGuide/markdown/BerichtSubsystem/BerichtSubsystem_Interaktionen.md?plain=1#L13

- [x] Die Vorgaben für die HTTP Return Messages in der Basis sollten (analog zur Änderung in der Terminplanung, vergleiche hier: https://github.com/gematik/spec-ISiK-Terminplanung/issues/121),  sowohl syntaktische als auch semantische Errors abdecken.
- [x] Auch die HTTP 2xx Codes sollten kohärent sein.
- [x] Ggf. auch an anderen stellen in der Basis zu lösen
- [x] Die bitte als PR für einen TC ausweisen und nicht direkt in main mergen

```[tasklist]
### Tasks
- [ ] PTDATA-704
```

**Comment by f-peverali** [comment]
umsetzen mit https://github.com/gematik/spec-ISiK-Basismodul/issues/312
